has_layout: true

layout:
  default

default:
  title: Página

  metas:
    http:
      content-type: text/html; charset=utf-9
      content-language: es-ES

    https:
      content-type: text/html; charset=utf-8
      content-language: es-ES

    name:
      keywords:
      description:
      robots: index, follow

  css:

  js:
    cdn:
      - https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min

